// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class EmailLogs
{
    public int Id { get; set; }

    public string CompanyName { get; set; }

    public string RecipientEmail { get; set; }

    public string SentStatus { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime? SentAt { get; set; }
}