// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class EmailMasters
{
    public int Id { get; set; }

    public string RecipientName { get; set; }

    public string EmailAddress { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }
}