// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PLCARD.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PLCARD.Models
{
    public partial interface IPLCARDContextProcedures
    {
        Task<List<sp_CleanOldSyncDataResult>> sp_CleanOldSyncDataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetCardRegistrationReportResult>> sp_GetCardRegistrationReportAsync(DateTime? fromDate, DateTime? toDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
