// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PLCARD.Models;

public partial class PLCARDContext : DbContext
{
    public PLCARDContext(DbContextOptions<PLCARDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblCardMaster> TblCardMasters { get; set; }

    public virtual DbSet<TblCardRegistration> TblCardRegistrations { get; set; }

    public virtual DbSet<TblCompanyRegistration> TblCompanyRegistrations { get; set; }

    public virtual DbSet<TblCorporatePlanMaster> TblCorporatePlanMasters { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblCardMaster>(entity =>
        {
            entity.HasKey(e => e.IntCard);

            entity.ToTable("tblCardMaster");

            entity.Property(e => e.IntCard).HasColumnName("intCard");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.Dtcreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtcreated");
            entity.Property(e => e.Dtupdated)
                .HasColumnType("datetime")
                .HasColumnName("dtupdated");
            entity.Property(e => e.FkBId).HasColumnName("fk_b_ID");
            entity.Property(e => e.Flambulanceipd).HasColumnName("flambulanceipd");
            entity.Property(e => e.Fldiagno).HasColumnName("fldiagno");
            entity.Property(e => e.Flhomecare).HasColumnName("flhomecare");
            entity.Property(e => e.Flipd).HasColumnName("flipd");
            entity.Property(e => e.Fllab).HasColumnName("fllab");
            entity.Property(e => e.Flopd).HasColumnName("flopd");
            entity.Property(e => e.Flpharmacy).HasColumnName("flpharmacy");
            entity.Property(e => e.Intcostcard).HasColumnName("intcostcard");
            entity.Property(e => e.VchCatCode)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("vchCatCode");
            entity.Property(e => e.Vchcname)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vchcname");
            entity.Property(e => e.Vchcreatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedby");
            entity.Property(e => e.Vchupdatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedby");
            entity.Property(e => e.Yr).HasColumnName("yr");
        });

        modelBuilder.Entity<TblCardRegistration>(entity =>
        {
            entity.HasKey(e => e.IntRegId);

            entity.ToTable("tblCardRegistration");

            entity.Property(e => e.IntRegId).HasColumnName("intRegID");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.DtDob)
                .HasColumnType("datetime")
                .HasColumnName("dtDOB");
            entity.Property(e => e.Dtcreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtcreated");
            entity.Property(e => e.Dtupdated)
                .HasColumnType("datetime")
                .HasColumnName("dtupdated");
            entity.Property(e => e.FkBId).HasColumnName("fk_b_ID");
            entity.Property(e => e.IntCardId).HasColumnName("intCardID");
            entity.Property(e => e.IntCharges).HasColumnName("intCharges");
            entity.Property(e => e.Intage).HasColumnName("intage");
            entity.Property(e => e.VchAddress)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("vch_address");
            entity.Property(e => e.VchCardRefBy)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchCardRefBy");
            entity.Property(e => e.VchCardType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchCardType");
            entity.Property(e => e.VchHmsRcpt)
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("vchHMS_Rcpt");
            entity.Property(e => e.VchUhidno)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vchUhidno");
            entity.Property(e => e.Vchcity)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcity");
            entity.Property(e => e.Vchcontactno)
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasColumnName("vchcontactno");
            entity.Property(e => e.Vchcreatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedby");
            entity.Property(e => e.Vchcreatedhost)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedhost");
            entity.Property(e => e.Vchemail)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchemail");
            entity.Property(e => e.Vchipused)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchipused");
            entity.Property(e => e.Vchname)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchname");
            entity.Property(e => e.Vchpincode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("vchpincode");
            entity.Property(e => e.VchsState)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchs_state");
            entity.Property(e => e.Vchsex)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("vchsex");
            entity.Property(e => e.VchspouseName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchspouseName");
            entity.Property(e => e.Vchupdatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedby");
            entity.Property(e => e.Vchupdatedhost)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedhost");
            entity.Property(e => e.Vchupdatedipused)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedipused");
            entity.Property(e => e.Yr).HasColumnName("yr");

            entity.HasOne(d => d.IntCard).WithMany(p => p.TblCardRegistrations)
                .HasForeignKey(d => d.IntCardId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CardReg_CardMaster");
        });

        modelBuilder.Entity<TblCompanyRegistration>(entity =>
        {
            entity.HasKey(e => e.IntCompanyId);

            entity.ToTable("tblCompanyRegistration");

            entity.Property(e => e.IntCompanyId).HasColumnName("intCompanyID");
            entity.Property(e => e.BitActive)
                .HasDefaultValue(true)
                .HasColumnName("bitActive");
            entity.Property(e => e.DtRegistration)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtRegistration");
            entity.Property(e => e.FkBId).HasColumnName("fk_b_ID");
            entity.Property(e => e.IntPlanId).HasColumnName("intPlanID");
            entity.Property(e => e.VchAgreementPath)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("vchAgreementPath");
            entity.Property(e => e.VchCompanyName)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("vchCompanyName");
            entity.Property(e => e.VchContactNo)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("vchContactNo");
            entity.Property(e => e.VchContactPerson)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchContactPerson");
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchCreatedBy");

            entity.HasOne(d => d.IntPlan).WithMany(p => p.TblCompanyRegistrations)
                .HasForeignKey(d => d.IntPlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Company_CorpPlan");
        });

        modelBuilder.Entity<TblCorporatePlanMaster>(entity =>
        {
            entity.HasKey(e => e.IntPlanId);

            entity.ToTable("tblCorporatePlanMaster");

            entity.Property(e => e.IntPlanId).HasColumnName("intPlanID");
            entity.Property(e => e.BitWellnessCamp)
                .HasDefaultValue(false)
                .HasColumnName("bitWellnessCamp");
            entity.Property(e => e.DtCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtCreated");
            entity.Property(e => e.FkBId).HasColumnName("fk_b_ID");
            entity.Property(e => e.FlAmbulance).HasColumnName("flAmbulance");
            entity.Property(e => e.FlDaycare).HasColumnName("flDaycare");
            entity.Property(e => e.FlEmergencyTest).HasColumnName("flEmergencyTest");
            entity.Property(e => e.FlIpd).HasColumnName("flIPD");
            entity.Property(e => e.FlLab).HasColumnName("flLab");
            entity.Property(e => e.FlOpdconsult).HasColumnName("flOPDConsult");
            entity.Property(e => e.FlOpdproc).HasColumnName("flOPDProc");
            entity.Property(e => e.FlPetCt).HasColumnName("flPetCt");
            entity.Property(e => e.FlRadiology).HasColumnName("flRadiology");
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchCreatedBy");
            entity.Property(e => e.VchExclusions)
                .IsUnicode(false)
                .HasColumnName("vchExclusions");
            entity.Property(e => e.VchPlanName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchPlanName");
            entity.Property(e => e.VchTier)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchTier");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}