// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PLCARD.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PLCARD.Models
{
    public partial class PLCARDContext
    {
        private IPLCARDContextProcedures _procedures;

        public virtual IPLCARDContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new PLCARDContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IPLCARDContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class PLCARDContextProcedures : IPLCARDContextProcedures
    {
        private readonly PLCARDContext _context;

        public PLCARDContextProcedures(PLCARDContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_CleanOldSyncDataResult>> sp_CleanOldSyncDataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_CleanOldSyncDataResult>("EXEC @returnValue = [dbo].[sp_CleanOldSyncData]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
