// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PLCARD.Models;

public partial class PLCARDContext : DbContext
{
    public PLCARDContext(DbContextOptions<PLCARDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblCardMaster> TblCardMaster { get; set; }

    public virtual DbSet<TblCardRegistration> TblCardRegistration { get; set; }

    public virtual DbSet<TblCompanyRegistration> TblCompanyRegistration { get; set; }

    public virtual DbSet<TblCorporatePlanMaster> TblCorporatePlanMaster { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_1xCompat_CP850_CI_AS");

        modelBuilder.Entity<TblCardMaster>(entity =>
        {
            entity.HasKey(e => e.IntCard).HasName("PK_tblCardMaster_1");

            entity.ToTable("tblCardMaster");

            entity.Property(e => e.IntCard).HasColumnName("intCard");
            entity.Property(e => e.BitActive).HasDefaultValue(true);
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.Dtcreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtcreated");
            entity.Property(e => e.Dtupdated)
                .HasColumnType("datetime")
                .HasColumnName("dtupdated");
            entity.Property(e => e.FkBId).HasColumnName("fk_b_ID");
            entity.Property(e => e.Flambulanceipd).HasColumnName("flambulanceipd");
            entity.Property(e => e.Fldiagno).HasColumnName("fldiagno");
            entity.Property(e => e.Flhomecare).HasColumnName("flhomecare");
            entity.Property(e => e.Flipd).HasColumnName("flipd");
            entity.Property(e => e.Fllab).HasColumnName("fllab");
            entity.Property(e => e.Flopd).HasColumnName("flopd");
            entity.Property(e => e.Flpharmacy).HasColumnName("flpharmacy");
            entity.Property(e => e.Intcostcard).HasColumnName("intcostcard");
            entity.Property(e => e.VchCatCode)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("vchCatCode");
            entity.Property(e => e.Vchcname)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vchcname");
            entity.Property(e => e.Vchcreatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedby");
            entity.Property(e => e.Vchupdatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedby");
            entity.Property(e => e.Yr).HasColumnName("yr");
        });

        modelBuilder.Entity<TblCardRegistration>(entity =>
        {
            entity.HasKey(e => e.IntRegId);

            entity.ToTable("tblCardRegistration");

            entity.Property(e => e.IntRegId).HasColumnName("intRegID");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.DtDob)
                .HasColumnType("datetime")
                .HasColumnName("dtDOB");
            entity.Property(e => e.Dtcreated)
                .HasDefaultValueSql("(getdate())", "DF__tblCardRe__dtcre__276EDEB3")
                .HasColumnType("datetime")
                .HasColumnName("dtcreated");
            entity.Property(e => e.Dtupdated)
                .HasColumnType("datetime")
                .HasColumnName("dtupdated");
            entity.Property(e => e.FkBId).HasColumnName("fk_b_ID");
            entity.Property(e => e.IntCardId).HasColumnName("intCardID");
            entity.Property(e => e.IntCharges).HasColumnName("intCharges");
            entity.Property(e => e.Intage).HasColumnName("intage");
            entity.Property(e => e.VchAddress)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("vch_address");
            entity.Property(e => e.VchCardRefBy)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchCardRefBy");
            entity.Property(e => e.VchCardType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchCardType");
            entity.Property(e => e.VchHmsRcpt)
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("vchHMS_Rcpt");
            entity.Property(e => e.VchUhidno)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vchUhidno");
            entity.Property(e => e.Vchcity)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcity");
            entity.Property(e => e.Vchcontactno)
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasColumnName("vchcontactno");
            entity.Property(e => e.Vchcreatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedby");
            entity.Property(e => e.Vchcreatedhost)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedhost");
            entity.Property(e => e.Vchemail)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchemail");
            entity.Property(e => e.Vchipused)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchipused");
            entity.Property(e => e.Vchname)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchname");
            entity.Property(e => e.Vchpincode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("vchpincode");
            entity.Property(e => e.VchsState)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchs_state");
            entity.Property(e => e.Vchsex)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("vchsex");
            entity.Property(e => e.VchspouseName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchspouseName");
            entity.Property(e => e.Vchupdatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedby");
            entity.Property(e => e.Vchupdatedhost)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedhost");
            entity.Property(e => e.Vchupdatedipused)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedipused");
            entity.Property(e => e.Yr).HasColumnName("yr");

            entity.HasOne(d => d.IntCard).WithMany(p => p.TblCardRegistration)
                .HasForeignKey(d => d.IntCardId)
                .HasConstraintName("FK_tblCardRegistration_tblCardMaster");
        });

        modelBuilder.Entity<TblCompanyRegistration>(entity =>
        {
            entity.HasKey(e => e.IntCompanyId);

            entity.Property(e => e.BitActive).HasDefaultValue(true);
            entity.Property(e => e.DtAgreementEnd).HasColumnType("datetime");
            entity.Property(e => e.DtAgreementStart).HasColumnType("datetime");
            entity.Property(e => e.DtCreated)
                .HasColumnType("datetime")
                .HasColumnName("dtCreated");
            entity.Property(e => e.DtRegistration)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DtUpdated).HasColumnType("datetime");
            entity.Property(e => e.FkBid).HasColumnName("FkBId");
            entity.Property(e => e.VchAgreementNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchAgreementPath)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.VchCity)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchCompanyName)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.VchContactNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.VchContactPerson)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchCreatedHost)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchDesignation)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchEmail)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchFullAddress)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.VchGstNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.VchPanNo)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.VchPincode)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.VchUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchUpdatedHost)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IntPlan).WithMany(p => p.TblCompanyRegistration)
                .HasForeignKey(d => d.IntPlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblCompanyRegistration_TblCorporatePlanMaster");
        });

        modelBuilder.Entity<TblCorporatePlanMaster>(entity =>
        {
            entity.HasKey(e => e.IntPlanId).HasName("PK__TblCorpo__60CE315AA3A526AA");

            entity.Property(e => e.BitActive).HasDefaultValue(true);
            entity.Property(e => e.BitDeleted).HasDefaultValue(false);
            entity.Property(e => e.DcAmbulance).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcHomecare).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcIpd).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcLab).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcOpdConsult).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcOpdProcedure).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcPharmacy).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcRadiology).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DtCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DtUpdated).HasColumnType("datetime");
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchPlanName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}