// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PLCARD.Models;

public partial class PLCARDContext : DbContext
{
    public PLCARDContext(DbContextOptions<PLCARDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRoleClaims> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserTokens> AspNetUserTokens { get; set; }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<TblCardMaster> TblCardMaster { get; set; }

    public virtual DbSet<TblCardRegistration> TblCardRegistration { get; set; }

    public virtual DbSet<TblCardRegistrationOld> TblCardRegistrationOld { get; set; }

    public virtual DbSet<TblCompanyRegistration> TblCompanyRegistration { get; set; }

    public virtual DbSet<TblCorporatePlanMaster> TblCorporatePlanMaster { get; set; }

    public virtual DbSet<TblGlobalSettings> TblGlobalSettings { get; set; }

    public virtual DbSet<TblServerRegistry> TblServerRegistry { get; set; }

    public virtual DbSet<TblSyncQueue> TblSyncQueue { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_1xCompat_CP850_CI_AS");

        modelBuilder.Entity<AspNetRoleClaims>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetRoles>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUserClaims>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogins>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.LoginProvider).HasMaxLength(128);
            entity.Property(e => e.ProviderKey).HasMaxLength(128);
            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserTokens>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.Property(e => e.LoginProvider).HasMaxLength(128);
            entity.Property(e => e.Name).HasMaxLength(128);

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUsers>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Role).WithMany(p => p.User)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRoles",
                    r => r.HasOne<AspNetRoles>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUsers>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<TblCardMaster>(entity =>
        {
            entity.HasKey(e => e.IntCard).HasName("PK_tblCardMaster_1");

            entity.ToTable("tblCardMaster");

            entity.Property(e => e.IntCard).HasColumnName("intCard");
            entity.Property(e => e.BitActive).HasDefaultValue(true);
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.Dtcreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtcreated");
            entity.Property(e => e.Dtupdated)
                .HasColumnType("datetime")
                .HasColumnName("dtupdated");
            entity.Property(e => e.FkBId).HasColumnName("fk_b_ID");
            entity.Property(e => e.Flambulanceipd).HasColumnName("flambulanceipd");
            entity.Property(e => e.Fldiagno).HasColumnName("fldiagno");
            entity.Property(e => e.Flhomecare).HasColumnName("flhomecare");
            entity.Property(e => e.Flipd).HasColumnName("flipd");
            entity.Property(e => e.Fllab).HasColumnName("fllab");
            entity.Property(e => e.Flopd).HasColumnName("flopd");
            entity.Property(e => e.Flpharmacy).HasColumnName("flpharmacy");
            entity.Property(e => e.Intcostcard).HasColumnName("intcostcard");
            entity.Property(e => e.VchCatCode)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("vchCatCode");
            entity.Property(e => e.Vchcname)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vchcname");
            entity.Property(e => e.Vchcreatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedby");
            entity.Property(e => e.Vchupdatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedby");
            entity.Property(e => e.Yr).HasColumnName("yr");
        });

        modelBuilder.Entity<TblCardRegistration>(entity =>
        {
            entity.HasKey(e => e.IntRegId);

            entity.ToTable("tblCardRegistration", tb => tb.HasTrigger("trg_SyncCardRegistration"));

            entity.Property(e => e.IntRegId).HasColumnName("intRegID");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.DtDob)
                .HasColumnType("datetime")
                .HasColumnName("dtDOB");
            entity.Property(e => e.Dtcreated)
                .HasColumnType("datetime")
                .HasColumnName("dtcreated");
            entity.Property(e => e.Dtupdated)
                .HasColumnType("datetime")
                .HasColumnName("dtupdated");
            entity.Property(e => e.FkBId).HasColumnName("fk_b_ID");
            entity.Property(e => e.IntCardId).HasColumnName("intCardID");
            entity.Property(e => e.IntCharges).HasColumnName("intCharges");
            entity.Property(e => e.Intage).HasColumnName("intage");
            entity.Property(e => e.VchAddress)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("vch_address");
            entity.Property(e => e.VchCardRefBy)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchCardRefBy");
            entity.Property(e => e.VchCardType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchCardType");
            entity.Property(e => e.VchHmsRcpt)
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("vchHMS_Rcpt");
            entity.Property(e => e.VchUhidno)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vchUhidno");
            entity.Property(e => e.Vchcity)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcity");
            entity.Property(e => e.Vchcontactno)
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasColumnName("vchcontactno");
            entity.Property(e => e.Vchcreatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedby");
            entity.Property(e => e.Vchcreatedhost)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedhost");
            entity.Property(e => e.Vchemail)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchemail");
            entity.Property(e => e.Vchipused)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchipused");
            entity.Property(e => e.Vchname)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchname");
            entity.Property(e => e.Vchpincode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("vchpincode");
            entity.Property(e => e.VchsState)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchs_state");
            entity.Property(e => e.Vchsex)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("vchsex");
            entity.Property(e => e.VchspouseName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchspouseName");
            entity.Property(e => e.Vchupdatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedby");
            entity.Property(e => e.Vchupdatedhost)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedhost");
            entity.Property(e => e.Vchupdatedipused)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedipused");
            entity.Property(e => e.Yr).HasColumnName("yr");

            entity.HasOne(d => d.IntCard).WithMany(p => p.TblCardRegistration)
                .HasForeignKey(d => d.IntCardId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblCardRegistration_tblCardMaster1");
        });

        modelBuilder.Entity<TblCardRegistrationOld>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("tblCardRegistration_old", tb => tb.HasTrigger("TR_Sync_CardRegistration"));

            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.DtDob)
                .HasColumnType("datetime")
                .HasColumnName("dtDOB");
            entity.Property(e => e.Dtcreated)
                .HasDefaultValueSql("(getdate())", "DF__tblCardRe__dtcre__276EDEB3")
                .HasColumnType("datetime")
                .HasColumnName("dtcreated");
            entity.Property(e => e.Dtupdated)
                .HasColumnType("datetime")
                .HasColumnName("dtupdated");
            entity.Property(e => e.FkBId).HasColumnName("fk_b_ID");
            entity.Property(e => e.IntCardId).HasColumnName("intCardID");
            entity.Property(e => e.IntCharges).HasColumnName("intCharges");
            entity.Property(e => e.IntRegId)
                .ValueGeneratedOnAdd()
                .HasColumnName("intRegID");
            entity.Property(e => e.Intage).HasColumnName("intage");
            entity.Property(e => e.VchAddress)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("vch_address");
            entity.Property(e => e.VchCardRefBy)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchCardRefBy");
            entity.Property(e => e.VchCardType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchCardType");
            entity.Property(e => e.VchHmsRcpt)
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("vchHMS_Rcpt");
            entity.Property(e => e.VchUhidno)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vchUhidno");
            entity.Property(e => e.Vchcity)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcity");
            entity.Property(e => e.Vchcontactno)
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasColumnName("vchcontactno");
            entity.Property(e => e.Vchcreatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedby");
            entity.Property(e => e.Vchcreatedhost)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchcreatedhost");
            entity.Property(e => e.Vchemail)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchemail");
            entity.Property(e => e.Vchipused)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchipused");
            entity.Property(e => e.Vchname)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchname");
            entity.Property(e => e.Vchpincode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("vchpincode");
            entity.Property(e => e.VchsState)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchs_state");
            entity.Property(e => e.Vchsex)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("vchsex");
            entity.Property(e => e.VchspouseName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchspouseName");
            entity.Property(e => e.Vchupdatedby)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedby");
            entity.Property(e => e.Vchupdatedhost)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedhost");
            entity.Property(e => e.Vchupdatedipused)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchupdatedipused");
            entity.Property(e => e.Yr).HasColumnName("yr");

            entity.HasOne(d => d.IntCard).WithMany()
                .HasForeignKey(d => d.IntCardId)
                .HasConstraintName("FK__tblCardRe__intCa__5765FF9A");
        });

        modelBuilder.Entity<TblCompanyRegistration>(entity =>
        {
            entity.HasKey(e => e.IntCompanyId);

            entity.ToTable(tb => tb.HasTrigger("trg_SyncCompanyToQueue"));

            entity.Property(e => e.BitActive).HasDefaultValue(true);
            entity.Property(e => e.DtAgreementEnd).HasColumnType("datetime");
            entity.Property(e => e.DtAgreementStart).HasColumnType("datetime");
            entity.Property(e => e.DtCreated)
                .HasColumnType("datetime")
                .HasColumnName("dtCreated");
            entity.Property(e => e.DtRegistration)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DtUpdated).HasColumnType("datetime");
            entity.Property(e => e.FkBid).HasColumnName("FkBId");
            entity.Property(e => e.VchAgreementNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchAgreementPath)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.VchCity)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchCompanyName)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.VchContactNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.VchContactPerson)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchCreatedHost)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchDesignation)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchEmail)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchFullAddress)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.VchGstNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.VchPanNo)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.VchPincode)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.VchUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchUpdatedHost)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IntPlan).WithMany(p => p.TblCompanyRegistration)
                .HasForeignKey(d => d.IntPlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TblCompanyRegistration_TblCorporatePlanMaster");
        });

        modelBuilder.Entity<TblCorporatePlanMaster>(entity =>
        {
            entity.HasKey(e => e.IntPlanId).HasName("PK__TblCorpo__60CE315AA3A526AA");

            entity.Property(e => e.BitActive).HasDefaultValue(true);
            entity.Property(e => e.BitDeleted).HasDefaultValue(false);
            entity.Property(e => e.DcAmbulance).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcHomecare).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcIpd).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcLab).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcOpdConsult).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcOpdProcedure).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcPharmacy).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DcRadiology).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DtCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DtUpdated).HasColumnType("datetime");
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.VchPlanName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VchUpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TblGlobalSettings>(entity =>
        {
            entity.HasKey(e => e.IntSettingId).HasName("PK__TblGloba__B1E6D2309DCE642D");

            entity.HasIndex(e => e.VchSettingKey, "UQ__TblGloba__F40814258359E342").IsUnique();

            entity.Property(e => e.DtUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.VchDescription).HasMaxLength(255);
            entity.Property(e => e.VchSettingKey).HasMaxLength(100);
        });

        modelBuilder.Entity<TblServerRegistry>(entity =>
        {
            entity.HasKey(e => e.IntServerId).HasName("PK__TblServe__8AF32E92AF5D43AD");

            entity.Property(e => e.BitIsActive).HasDefaultValue(true, "DF__TblServer__BitIs__160F4887");
            entity.Property(e => e.DtCreated)
                .HasDefaultValueSql("(getdate())", "DF__TblServer__DtCre__17036CC0")
                .HasColumnType("datetime");
            entity.Property(e => e.DtLastCardSync).HasColumnType("datetime");
            entity.Property(e => e.DtLastCorpSync).HasColumnType("datetime");
            entity.Property(e => e.DtLastMasterSync).HasColumnType("datetime");
            entity.Property(e => e.DtLastSync).HasColumnType("datetime");
            entity.Property(e => e.VchApiKey).HasMaxLength(100);
            entity.Property(e => e.VchApiUrl)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.VchApihealth)
                .HasMaxLength(255)
                .HasColumnName("vchAPIHealth");
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .HasDefaultValue("Admin", "DF__TblServer__VchCr__17F790F9");
            entity.Property(e => e.VchLocation)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.VchServerName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TblSyncQueue>(entity =>
        {
            entity.HasKey(e => e.IntQueueId).HasName("PK__TblSyncQ__78869AF6D82396EA");

            entity.HasIndex(e => new { e.IntServerId, e.BitProcessed }, "IX_SyncQueue_Pending").HasFilter("([BitProcessed]=(0))");

            entity.Property(e => e.BitProcessed).HasDefaultValue(false);
            entity.Property(e => e.DtAdded)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IntRetryCount).HasDefaultValue(0);
            entity.Property(e => e.VchModule)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.IntServer).WithMany(p => p.TblSyncQueue)
                .HasForeignKey(d => d.IntServerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Queue_Server");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}