// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class ServerMaster
{
    public int IntServerId { get; set; }

    public string VchServerName { get; set; }

    public string VchLocation { get; set; }

    public bool? BitIsActive { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public virtual ICollection<TblHubServiceEndpoints> TblHubServiceEndpoints { get; set; } = new List<TblHubServiceEndpoints>();

    public virtual ICollection<TblSyncQueue> TblSyncQueue { get; set; } = new List<TblSyncQueue>();
}