// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PLCARD.Models
{
    public partial class sp_GetCardRegistrationReportResult
    {
        public DateTime? dtcreated { get; set; }
        [StringLength(20)]
        public string vchUhidno { get; set; }
        [StringLength(50)]
        public string vchname { get; set; }
        [StringLength(50)]
        public string vchCardType { get; set; }
        [StringLength(13)]
        public string vchcontactno { get; set; }
        [StringLength(10)]
        public string vchsex { get; set; }
        public int? intage { get; set; }
        public int? intCharges { get; set; }
        public int intRegID { get; set; }
        [StringLength(50)]
        public string vchcity { get; set; }
    }
}
