// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PLCARD.Models
{
    public partial class sp_GetCardRegistrationReportResult
    {
        public int IntRegId { get; set; }
        public DateTime? Dtcreated { get; set; }
        [StringLength(20)]
        public string VchUhidno { get; set; }
        [StringLength(50)]
        public string Vchname { get; set; }
        [StringLength(50)]
        public string VchCardType { get; set; }
        [StringLength(13)]
        public string Vchcontactno { get; set; }
        [StringLength(10)]
        public string Vchsex { get; set; }
        public int? Intage { get; set; }
        public int? IntCharges { get; set; }
        [StringLength(50)]
        public string Vchcity { get; set; }
    }
}
