// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class TblCorporatePlanMaster
{
    public int IntPlanId { get; set; }

    public string VchPlanName { get; set; }

    public string VchTier { get; set; }

    public float? FlOpdconsult { get; set; }

    public float? FlOpdproc { get; set; }

    public float? FlIpd { get; set; }

    public float? FlEmergencyTest { get; set; }

    public float? FlAmbulance { get; set; }

    public float? FlDaycare { get; set; }

    public float? FlLab { get; set; }

    public float? FlRadiology { get; set; }

    public float? FlPetCt { get; set; }

    public bool? BitWellnessCamp { get; set; }

    public string VchExclusions { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public int? FkBId { get; set; }

    public virtual ICollection<TblCompanyRegistration> TblCompanyRegistrations { get; set; } = new List<TblCompanyRegistration>();
}