// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class TblCardRegistrationOld
{
    public int IntRegId { get; set; }

    public int? IntCardId { get; set; }

    public string VchHmsRcpt { get; set; }

    public string VchCardType { get; set; }

    public string VchUhidno { get; set; }

    public string Vchname { get; set; }

    public DateTime? DtDob { get; set; }

    public string Vchsex { get; set; }

    public int? Intage { get; set; }

    public string VchspouseName { get; set; }

    public string Vchemail { get; set; }

    public string VchsState { get; set; }

    public string Vchcity { get; set; }

    public string VchAddress { get; set; }

    public string Vchcontactno { get; set; }

    public int? IntCharges { get; set; }

    public string Vchpincode { get; set; }

    public string VchCardRefBy { get; set; }

    public DateTime? Dtcreated { get; set; }

    public string Vchcreatedby { get; set; }

    public string Vchcreatedhost { get; set; }

    public string Vchipused { get; set; }

    public DateTime? Dtupdated { get; set; }

    public string Vchupdatedby { get; set; }

    public string Vchupdatedhost { get; set; }

    public string Vchupdatedipused { get; set; }

    public int? Code { get; set; }

    public int? Yr { get; set; }

    public int? FkBId { get; set; }

    public virtual TblCardMaster IntCard { get; set; }
}