// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class TblCompanyRegistration
{
    public int IntCompanyId { get; set; }

    public string VchCompanyName { get; set; }

    public int IntPlanId { get; set; }

    public string VchAgreementPath { get; set; }

    public DateTime? DtRegistration { get; set; }

    public bool? BitActive { get; set; }

    public string VchContactPerson { get; set; }

    public string VchContactNo { get; set; }

    public string VchCreatedBy { get; set; }

    public int? FkBId { get; set; }

    public virtual TblCorporatePlanMaster IntPlan { get; set; }
}