// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class TblCorporatePlanMaster
{
    public int IntPlanId { get; set; }

    public string VchPlanName { get; set; }

    public decimal? DcOpdConsult { get; set; }

    public decimal? DcOpdProcedure { get; set; }

    public decimal? DcRadiology { get; set; }

    public decimal? DcLab { get; set; }

    public decimal? DcPharmacy { get; set; }

    public decimal? DcHomecare { get; set; }

    public decimal? DcIpd { get; set; }

    public decimal? DcAmbulance { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public bool? BitActive { get; set; }

    public bool? BitDeleted { get; set; }

    public virtual ICollection<TblCompanyRegistration> TblCompanyRegistration { get; set; } = new List<TblCompanyRegistration>();
}