// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class TblCardMaster
{
    public int IntCard { get; set; }

    public string Vchcname { get; set; }

    public float? Flopd { get; set; }

    public float? Flipd { get; set; }

    public float? Fldiagno { get; set; }

    public float? Fllab { get; set; }

    public float? Flpharmacy { get; set; }

    public float? Flhomecare { get; set; }

    public float? Flambulanceipd { get; set; }

    public int? Intcostcard { get; set; }

    public int? Code { get; set; }

    public int? Yr { get; set; }

    public string Vchcreatedby { get; set; }

    public DateTime? Dtcreated { get; set; }

    public string Vchupdatedby { get; set; }

    public DateTime? Dtupdated { get; set; }

    public string VchCatCode { get; set; }

    public int? FkBId { get; set; }

    public bool BitActive { get; set; }

    public virtual ICollection<TblCardRegistration> TblCardRegistration { get; set; } = new List<TblCardRegistration>();
}