// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class TblGlobalSettings
{
    public int IntSettingId { get; set; }

    public string VchSettingKey { get; set; }

    public string VchSettingValue { get; set; }

    public string VchDescription { get; set; }

    public DateTime? DtUpdated { get; set; }
}