// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class TblHubServiceEndpoints
{
    public int IntEndpointId { get; set; }

    public int IntServerId { get; set; }

    public int ServiceTypeId { get; set; }

    public string VchEndpointUrl { get; set; }

    public DateTime? DtLastUpdated { get; set; }

    public virtual ServerMaster IntServer { get; set; }

    public virtual ServiceTypeMaster ServiceType { get; set; }
}