// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class TblSyncQueue
{
    public long IntQueueId { get; set; }

    public int IntServerId { get; set; }

    public string VchModule { get; set; }

    public int IntRecordId { get; set; }

    public int? IntRetryCount { get; set; }

    public bool? BitProcessed { get; set; }

    public DateTime? DtAdded { get; set; }

    public string VchErrorLog { get; set; }

    public virtual TblServerRegistry IntServer { get; set; }
}