// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLCARD.Models;

public partial class TblServerRegistry
{
    public int IntServerId { get; set; }

    public string VchServerName { get; set; }

    public string VchLocation { get; set; }

    public string VchApiUrl { get; set; }

    public string VchApiKey { get; set; }

    public DateTime? DtLastCardSync { get; set; }

    public DateTime? DtLastCorpSync { get; set; }

    public DateTime? DtLastMasterSync { get; set; }

    public DateTime? DtLastSync { get; set; }

    public bool? BitIsActive { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public virtual ICollection<TblSyncQueue> TblSyncQueue { get; set; } = new List<TblSyncQueue>();
}